"""Compaction and branch-summarization utilities."""

from .branch_summarization import (
    BranchPreparation,
    BranchSummaryResult,
    CollectEntriesResult,
    GenerateBranchSummaryOptions,
    collect_entries_for_branch_summary,
    generate_branch_summary,
    prepare_branch_entries,
)
from .compaction import (
    CompactionDetails,
    CompactionPreparation,
    CompactionResult,
    CompactionSettings,
    ContextUsageEstimate,
    DEFAULT_COMPACTION_SETTINGS,
    calculate_context_tokens,
    compact,
    estimate_context_tokens,
    estimate_tokens,
    find_cut_point,
    generate_summary,
    prepare_compaction,
    should_compact,
)
from .utils import (
    FileOperations,
    SUMMARIZATION_SYSTEM_PROMPT,
    compute_file_lists,
    create_file_ops,
    extract_file_ops_from_message,
    format_file_operations,
    serialize_conversation,
)

__all__ = [
    "BranchPreparation",
    "BranchSummaryResult",
    "CollectEntriesResult",
    "CompactionDetails",
    "CompactionPreparation",
    "CompactionResult",
    "CompactionSettings",
    "ContextUsageEstimate",
    "DEFAULT_COMPACTION_SETTINGS",
    "FileOperations",
    "GenerateBranchSummaryOptions",
    "SUMMARIZATION_SYSTEM_PROMPT",
    "calculate_context_tokens",
    "collect_entries_for_branch_summary",
    "compact",
    "compute_file_lists",
    "create_file_ops",
    "estimate_context_tokens",
    "estimate_tokens",
    "extract_file_ops_from_message",
    "find_cut_point",
    "format_file_operations",
    "generate_branch_summary",
    "generate_summary",
    "prepare_branch_entries",
    "prepare_compaction",
    "serialize_conversation",
    "should_compact",
]
