"""Claude Code-style synthetic message pattern helpers."""

from __future__ import annotations

import html
import time
from collections.abc import Mapping

from pydantic import BaseModel, ConfigDict

from agentm.core.abi.manifest import AtomInstallPriority
from agentm.core.abi.messages import (
    InterruptionMessagePolicy,
    MessageMeta,
    TextContent,
    ToolResultBlock,
    ToolResultMessage,
    UserMessage,
)
from agentm.core.abi.roles import INTERRUPTION_MESSAGE_POLICY_SERVICE
from agentm.core.abi.session_api import AtomAPI
from agentm.extensions import ExtensionManifest


MESSAGE_PATTERNS_SERVICE = INTERRUPTION_MESSAGE_POLICY_SERVICE
INTERRUPT_MESSAGE = "[Request interrupted by user]"
INTERRUPT_MESSAGE_FOR_TOOL_USE = "[Request interrupted by user for tool use]"
TOOL_INTERRUPTED = "Interrupted by user"
NO_RESPONSE_REQUESTED = "No response requested."
CANCEL_MESSAGE = (
    "The user doesn't want to take this action right now. STOP what you are "
    "doing and wait for the user to tell you how to proceed."
)
REJECT_MESSAGE = (
    "The user doesn't want to proceed with this tool use. The tool use was "
    "rejected. STOP what you are doing and wait for the user to tell you how "
    "to proceed."
)
SUBAGENT_REJECT_MESSAGE = (
    "Permission for this tool use was denied. The tool use was rejected. Try a "
    "different approach or report the limitation to complete your task."
)
PLAN_REJECTION_PREFIX = (
    "The agent proposed a plan that was rejected by the user. The user chose "
    "to stay in plan mode rather than proceed with implementation.\n\n"
    "Rejected plan:\n"
)
LOCAL_COMMAND_CAVEAT = (
    "Caveat: The messages below were generated by the user while running local "
    "commands. DO NOT respond to these messages unless the user explicitly asks."
)


class MessagePatternsConfig(BaseModel):
    model_config = ConfigDict(extra="forbid")


MANIFEST = ExtensionManifest(
    name="message_patterns",
    description="Render synthetic messages for interrupted model and tool work.",
    registers=("service:interruption_message_policy",),
    config_schema=MessagePatternsConfig,
    requires=(),
    priority=AtomInstallPriority.CONTEXT,
)


class MessagePatternFactory:
    """Factory for provider-facing synthetic/user-side control messages."""

    def interruption_message(
        self,
        reason: str,
        *,
        for_tool_use: bool = False,
    ) -> UserMessage | None:
        if reason == "submit_interrupt":
            return None
        text = INTERRUPT_MESSAGE_FOR_TOOL_USE if for_tool_use else INTERRUPT_MESSAGE
        return _synthetic(text, kind="interrupt", origin="runtime")

    def interrupt(self, *, for_tool_use: bool = False) -> UserMessage:
        message = self.interruption_message(
            "user_cancel",
            for_tool_use=for_tool_use,
        )
        assert message is not None
        return message

    def interrupted_tool_result(
        self,
        tool_call_id: str,
        reason: str,
    ) -> ToolResultBlock:
        del reason
        return ToolResultBlock(
            type="tool_result",
            tool_call_id=tool_call_id,
            content=[TextContent(type="text", text=TOOL_INTERRUPTED)],
            is_error=True,
        )

    def missing_tool_result(self, tool_call_id: str) -> ToolResultMessage:
        return ToolResultMessage(
            role="tool_result",
            content=[self.interrupted_tool_result(tool_call_id, "user_cancel")],
            timestamp=time.time(),
            meta=MessageMeta(
                synthetic=True,
                synthetic_kind="interrupted_tool_result",
                origin="runtime",
                visibility="hidden",
                tags={"interrupted": True},
            ),
        )

    def cancel(self) -> UserMessage:
        return _synthetic(CANCEL_MESSAGE, kind="permission_cancel", origin="permission")

    def permission_rejection(
        self,
        *,
        reason: str | None = None,
        subagent: bool = False,
    ) -> UserMessage:
        text = SUBAGENT_REJECT_MESSAGE if subagent else REJECT_MESSAGE
        if reason:
            text = f"{text}\n\nReason: {reason}"
        return _synthetic(text, kind="permission_rejection", origin="permission")

    def auto_rejection(
        self, tool_name: str, *, reason: str | None = None
    ) -> UserMessage:
        text = f"Permission to use {tool_name} has been denied."
        if reason:
            text = f"{text} Reason: {reason}"
        return _synthetic(text, kind="permission_auto_rejection", origin="permission")

    def plan_rejection(self, rejected_plan: str) -> UserMessage:
        return _synthetic(
            PLAN_REJECTION_PREFIX + rejected_plan,
            kind="plan_rejection",
            origin="presenter",
            mode="plan",
        )

    def no_response_requested(self) -> UserMessage:
        return _synthetic(
            NO_RESPONSE_REQUESTED,
            kind="no_response_requested",
            origin="presenter",
            no_response_requested=True,
        )

    def task_notification(
        self,
        *,
        task_id: str,
        status: str,
        summary: str,
        result: str = "",
        tool_use_id: str | None = None,
        output_file: str | None = None,
        usage: Mapping[str, str | int | float | bool | None] | None = None,
        worktree: Mapping[str, str] | None = None,
        target_agent_id: str | None = None,
    ) -> UserMessage:
        parts = [
            "<task-notification>",
            _xml_tag("task-id", task_id),
        ]
        if tool_use_id:
            parts.append(_xml_tag("tool-use-id", tool_use_id))
        if output_file:
            parts.append(_xml_tag("output-file", output_file))
        parts.extend(
            [
                _xml_tag("status", status),
                _xml_tag("summary", summary),
                _xml_tag("result", result),
            ]
        )
        if usage:
            parts.append("<usage>")
            for key, value in usage.items():
                if value is not None:
                    parts.append(_xml_tag(str(key), str(value)))
            parts.append("</usage>")
        if worktree:
            parts.append("<worktree>")
            for key, value in worktree.items():
                parts.append(_xml_tag(str(key), value))
            parts.append("</worktree>")
        parts.append("</task-notification>")
        return _synthetic(
            "\n".join(parts),
            kind="task_notification",
            origin="task",
            mode="task-notification",
            target_agent_id=target_agent_id,
        )

    def local_command(
        self,
        *,
        command_name: str,
        command_message: str = "",
        command_args: str = "",
        stdout: str = "",
        stderr: str = "",
    ) -> list[UserMessage]:
        command = "".join(
            [
                _xml_tag("command-name", command_name),
                _xml_tag("command-message", command_message),
                _xml_tag("command-args", command_args),
            ]
        )
        messages = [
            _synthetic(
                _xml_tag("local-command-caveat", LOCAL_COMMAND_CAVEAT),
                kind="local_command_caveat",
                origin="presenter",
                no_response_requested=True,
            ),
            _synthetic(command, kind="local_command", origin="presenter"),
        ]
        if stdout:
            messages.append(
                _synthetic(
                    _xml_tag("local-command-stdout", stdout),
                    kind="local_command_stdout",
                    origin="presenter",
                )
            )
        if stderr:
            messages.append(
                _synthetic(
                    _xml_tag("local-command-stderr", stderr),
                    kind="local_command_stderr",
                    origin="presenter",
                )
            )
        return messages

    def attachment(
        self,
        kind: str,
        body: str,
        *,
        origin: str = "attachment",
        target_agent_id: str | None = None,
    ) -> UserMessage:
        return _synthetic(
            _xml_tag(kind, body),
            kind=kind,
            origin=origin,
            target_agent_id=target_agent_id,
        )

    def teammate_message(
        self,
        body: str,
        *,
        target_agent_id: str | None = None,
        channel: str | None = None,
    ) -> UserMessage:
        tag = "channel-message" if channel else "teammate-message"
        text = (
            f"<{tag}>\n{_xml_tag('channel', channel)}\n{html.escape(body)}\n</{tag}>"
            if channel
            else _xml_tag(tag, body)
        )
        return _synthetic(
            text,
            kind=tag,
            origin="teammate",
            target_agent_id=target_agent_id,
        )


def install(api: AtomAPI, config: MessagePatternsConfig) -> None:
    del config
    factory = MessagePatternFactory()
    api.services.register(
        MESSAGE_PATTERNS_SERVICE,
        factory,
        InterruptionMessagePolicy,
        scope="tree",
    )


def _synthetic(
    text: str,
    *,
    kind: str,
    origin: str,
    mode: str | None = None,
    target_agent_id: str | None = None,
    no_response_requested: bool = False,
) -> UserMessage:
    return UserMessage(
        role="user",
        content=[TextContent(type="text", text=text)],
        timestamp=time.time(),
        meta=MessageMeta(
            synthetic=True,
            synthetic_kind=kind,
            origin=origin,
            visibility="hidden",
            no_response_requested=no_response_requested,
            mode=mode,
            target_agent_id=target_agent_id,
            tags={"message_pattern": kind},
        ),
    )


def _xml_tag(tag: str, body: str | None) -> str:
    return f"<{tag}>{html.escape(body or '')}</{tag}>"


__all__ = [
    "INTERRUPT_MESSAGE",
    "INTERRUPT_MESSAGE_FOR_TOOL_USE",
    "MESSAGE_PATTERNS_SERVICE",
    "MessagePatternFactory",
    "install",
    "MANIFEST",
]
