"""Fail-stop: audit_replay sidecar filename must match the persisted
``SessionManager`` JSONL filename so ``agent-from-reminder`` can globe
the source session on real live runs.

Before this fix, the adapter used ``api.root_session_id`` (the OTel
trace_id, generated by the substrate at session-construction time) which
diverges from ``SessionManager.header.id`` (the persisted JSONL stem)
for every real session. This test pins the chosen id to the manager
header so the two filenames stay aligned.
"""

from __future__ import annotations

from pathlib import Path
from unittest.mock import MagicMock

from agentm.core.abi import LoopConfig
from agentm.core.runtime.session_helpers import SessionView
from agentm.core.runtime.session_manager import SessionManager

from llmharness.adapters.agentm import _audit_session_id


def _make_session_view(tmp_path: Path) -> tuple[SessionView, SessionManager]:
    session_dir = tmp_path / ".agentm" / "sessions"
    session_dir.mkdir(parents=True)
    mgr = SessionManager.create(str(tmp_path), session_dir)
    view = SessionView(mgr, loop_config_getter=lambda: LoopConfig())
    return view, mgr


def test_audit_session_id_uses_manager_header_id_on_persisted_session(
    tmp_path: Path,
) -> None:
    view, mgr = _make_session_view(tmp_path)
    persisted_id = mgr.get_session_id()
    assert persisted_id, "JsonlSessionManager.create should assign a header id"
    # Sanity: the persisted file name actually contains the header id.
    session_file = mgr.session_file
    assert session_file is not None
    assert persisted_id in session_file.name

    api = MagicMock()
    api.session = view
    # Trace id deliberately different — it's what we'd otherwise miswrite.
    api.root_session_id = "deadbeef" * 4

    chosen = _audit_session_id(api)

    assert chosen == persisted_id, (
        "audit_replay sidecar id must match the persisted SessionManager "
        "header id so agent-from-reminder can relocate the source session"
    )


