"""Centralized default values for AgentM configuration."""

# Network
DEFAULT_DASHBOARD_PORT: int = 8765

# Agent loop limits
DEFAULT_MAX_STEPS: int = 100
DEFAULT_ANALYZE_MAX_STEPS: int = 60
DEFAULT_TIMEOUT_SECONDS: float = 600.0

# Token / budget limits
DEFAULT_MAX_CHUNK_TOKENS: int = 100_000
DEFAULT_TOOL_RESULT_BUDGET: int = 30_000
DEFAULT_TOTAL_RESULT_BUDGET: int = 150_000
DEFAULT_MIN_RESULT_BUDGET: int = 2_000
DEFAULT_TOOL_TOKEN_LIMIT: int = 5000
DEFAULT_TRAJECTORY_TRUNCATION: int = 8000

# Concurrency
DEFAULT_MAX_TOOL_CONCURRENCY: int = 8

# Display
DEFAULT_VERBOSE_CONTENT_LIMIT: int = 2000
DEFAULT_CONTENT_LIMIT: int = 500

# Middleware
DEFAULT_STALE_AFTER_STEPS: int = 6
DEFAULT_ABORT_WAIT_TIMEOUT: float = 1.0

# Orchestrator
DEFAULT_CHECK_TASKS_WAIT_SECONDS: float = 600.0

# Server
DEFAULT_SERVER_STARTUP_WAIT: float = 0.3
